server:
  port: 8086
  servlet:
    context-path: /springbootconsumer

spring:
  application:
    name: spring-boot-consumer-feign-hystrix
  zipkin:
    base-url: http://localhost:8092
    sender:
      type: web

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/springcloudeureka/eureka/

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
